const ruleSeedData = [
  {
    _id: "624a6a677c8d9c9f5fd5eb2b",
    title: "CodeCrafters Community Guidelines",
    description: "1. Be respectful and supportive of fellow coders.",
    reportReason: "Violation of community guidelines",
    communityName: "CodeCrafters",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb2c",
    title: "TechTalks Community Guidelines",
    description: "1. Engage in constructive discussions about technology trends and innovations.",
    reportReason: "Violation of community guidelines",
    communityName: "TechTalks",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb2d",
    title: "CodeGeeks Community Guidelines",
    description: "1. Collaborate respectfully on coding projects and challenges.",
    reportReason: "Violation of community guidelines",
    communityName: "CodeGeeks",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb2e",
    title: "Science Explorers Club Community Guidelines",
    description: "1. Share and discuss scientific topics with an open mind and respect for diverse perspectives.",
    reportReason: "Violation of community guidelines",
    communityName: "Science Explorers Club",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb2f",
    title: "Space & Astronomy Lovers Community Guidelines",
    description: "1. Share and discuss astronomical topics with enthusiasm and curiosity.",
    reportReason: "Violation of community guidelines",
    communityName: "Space & Astronomy Lovers",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb30",
    title: "Biology Buffs Society Community Guidelines",
    description: "1. Respectfully discuss and explore various aspects of biology.",
    reportReason: "Violation of community guidelines",
    communityName: "Biology Buffs Society",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb31",
    title: "Creative Minds Collective Community Guidelines",
    description: "1. Share creative works and ideas with positivity and constructive feedback.",
    reportReason: "Violation of community guidelines",
    communityName: "Creative Minds Collective",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb32",
    title: "Visual Arts Gallery Community Guidelines",
    description: "1. Respect and appreciate diverse forms of visual art.",
    reportReason: "Violation of community guidelines",
    communityName: "Visual Arts Gallery",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb33",
    title: "Writers' Haven Community Guidelines",
    description: "1. Provide constructive feedback and support to fellow writers.",
    reportReason: "Violation of community guidelines",
    communityName: "Writers' Haven",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb34",
    title: "Mindfulness & Meditation Community Guidelines",
    description: "1. Practice mindfulness and engage in meditation discussions with empathy and kindness.",
    reportReason: "Violation of community guidelines",
    communityName: "Mindfulness & Meditation Community",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb35",
    title: "Mental Health Support Group Community Guidelines",
    description: "1. Respect the privacy and emotions of members when discussing mental health issues.",
    reportReason: "Violation of community guidelines",
    communityName: "Mental Health Support Group",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb3e",
    title: "Psychology Insights Circle Community Guidelines",
    description: "1. Discuss psychological topics with empathy and respect for diverse viewpoints.",
    reportReason: "Violation of community guidelines",
    communityName: "Psychology Insights Circle",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb37",
    title: "Globetrotters Community Guidelines",
    description: "1. Share travel experiences and advice while respecting different cultures and perspectives.",
    reportReason: "Violation of community guidelines",
    communityName: "Globetrotters Community",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb38",
    title: "Adventurous Souls Society Community Guidelines",
    description: "1. Encourage responsible and respectful travel behavior.",
    reportReason: "Violation of community guidelines",
    communityName: "Adventurous Souls Society",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb39",
    title: "Culinary Delights Community Guidelines",
    description: "1. Share culinary experiences and recipes with enthusiasm and positivity.",
    reportReason: "Violation of community guidelines",
    communityName: "Culinary Delights",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb3a",
    title: "Gourmet Adventures Community Guidelines",
    description: "1. Appreciate and celebrate diverse culinary cultures and cuisines.",
    reportReason: "Violation of community guidelines",
    communityName: "Gourmet Adventures",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb3b",
    title: "Pop Culture Fanatics Community Guidelines",
    description: "1. Respect and appreciate various forms of popular culture without discrimination.",
    reportReason: "Violation of community guidelines",
    communityName: "Pop Culture Fanatics",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb3c",
    title: "Movie Buffs Club Community Guidelines",
    description: "1. Engage in respectful and insightful discussions about films.",
    reportReason: "Violation of community guidelines",
    communityName: "Movie Buffs Club",
  },
  {
    _id: "624a6a677c8d9c9f5fd5eb3d",
    title: "Music Maniacs Lounge Community Guidelines",
    description: "1. Share and appreciate diverse musical tastes and genres with respect for fellow members.",
    reportReason: "Violation of community guidelines",
    communityName: "Music Maniacs Lounge",
  },
];

exports.data = ruleSeedData;
